clear;

% class contaning the physical properties of the system
config = Config(struct('N', 8*10^4,... % the amount of condensted particles
                       'ChE', 'Rb87', ... % chemical element: Rb87/Na23
                       'gamma', 0.03, ... % dissipation parameters
                       'T', 1.4398*10^(-7), ...
                       'mu', 2.7137*10^(-30))); % temperature
                   %'T', 1.4398*10^(-7)));%, ...

grid = Grid(struct('GPU', 1, ...
                   'N', 6*128/4,...
                   'Nz', 6*32/4, ...
                   'L', 6*15*10^(-6),...
                   'Lz', 6*(15/4)*10^(-6)));

phase = Phase(struct('R_min', 16*10^(-6), ... 
                     'n', 3, ...
                     'grid', grid));
            
                         
Vt = PotentialToroidal(struct('wr', 2*pi*150, ...
                              'wz', 2*pi*600, ...
                              'nRings', 1, ...
                              'R', 0, ... %'R2', 13*10^(-6), ... 
                              'grid', grid, ...
                              'config', config));

[Psi, nt] = Init(struct('phase', phase, ...
                        'Vt', Vt, ...
                        'grid', grid, ...
                        'config', config)).getZNG3(); 


%clf;
%isosurface(grid.X, grid.Y, grid.Z, abs(Psi).^2, 10^(19))
 %imagesc(grid.r, grid.rz, squeeze(abs(Psi(:, grid.N/2, :).^2)))
%imagesc(grid.r, grid.r, abs(Psi(:, :, grid.Nz/2).^2))
%colorbar;
%shg