function V = getV(obj)
if obj.nRings == 1
    V = 0.5*obj.config.M*(...
            obj.wr^2*((obj.grid.X.^2 + obj.grid.Y.^2).^0.5 - obj.R).^2 + ...
            obj.wz^2*obj.grid.Z.^2);
        
elseif obj.nRings == 2
    U1 = ((sqrt(obj.grid.X.^2 + obj.grid.Y.^2) - obj.R).^2).*...
         ((obj.grid.X.^2 + obj.grid.Y.^2) > obj.R^2);
    U2 = min((sqrt(obj.grid.X.^2 + obj.grid.Y.^2) - obj.R).^2, ...
             (sqrt(obj.grid.X.^2 + obj.grid.Y.^2) - obj.R2).^2).*...
                  ((obj.grid.X.^2 + obj.grid.Y.^2) < obj.R^2).*...
                  ((obj.grid.X.^2 + obj.grid.Y.^2) > obj.R2^2);
    U3 =((sqrt(obj.grid.X.^2 + obj.grid.Y.^2) - obj.R2).^2).*...
             ((obj.grid.X.^2 + obj.grid.Y.^2) < obj.R2^2);

    Vr = 0.5*obj.config.M*obj.wr^2*(U1 + U2 + U3);
    Vz = 0.5*obj.config.M*obj.wz^2*obj.grid.Z.^2;
    V = Vr + Vz;
end
end